version: "3.4"
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports: 
      - "8081:8081"
    volumes:
      - type: volume
        source: artifactory-data
        target: /var/opt/jfrog/artifactory

volumes: 
  artifactory-data: