version: "3.4"

services: 
  my-mysql:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes: 
      - my-volume:/var/lib/mysql

  api:
    image: nginx:1.12-alpine

volumes: 
  my-volume: